import Head from "next/head";

import Dashboard from "@/components/Dashboard/Dashboard";

const DashboardPage = (props) => {
  return (
    <>
      <Head>
        <title>RBAC App | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </>
  );
};

export default DashboardPage;
