import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import Login from "@/components/Login/Login";

export default function Home() {
  return (
    <>
      <Head>
        <title>RBAC App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Login />
      </div>
    </>
  );
}
